//! Bulk upload endpoints for business applications.
//!
//! Provides:
//! - `GET  /api/v1/applications/bulk-upload/template` — download an Excel template
//! - `POST /api/v1/applications/bulk-upload`           — upload filled-in template
//!
//! No AI enrichment is triggered on bulk-uploaded applications (explicit requirement).
//! Each row is processed independently — partial success is supported.
//! Application code is auto-generated by DB trigger (not included in template).

use axum::Extension;
use axum::body::Body;
use axum::extract::{Multipart, State};
use axum::http::{StatusCode, header};
use axum::response::Response;
use calamine::{Data, Reader, Xlsx, open_workbook_from_rs};
use rust_xlsxwriter::{DataValidation, Format, FormatAlign, FormatBorder, Formula, Workbook};
use sqlx::PgPool;
use std::io::Cursor;
use uuid::Uuid;

use crate::auth::Claims;
use crate::db::AppState;
use crate::domain::glossary::{BulkUploadError, BulkUploadResult};
use crate::error::{AppError, AppResult};
use crate::workflow;

/// Maximum upload file size: 10 MB.
const MAX_FILE_SIZE: usize = 10 * 1024 * 1024;
/// Maximum data rows to process.
const MAX_ROWS: usize = 1000;

/// Column headers in the Applications sheet (A-P = 16 columns).
const TEMPLATE_HEADERS: &[&str] = &[
    "Application Name",      // A  (0)
    "Description",           // B  (1)
    "Classification",        // C  (2)
    "Vendor",                // D  (3)
    "Vendor Product Name",   // E  (4)
    "Deployment Type",       // F  (5)
    "Lifecycle Stage",       // G  (6)
    "License Type",          // H  (7)
    "Business Owner",        // I  (8)
    "Technical Owner",       // J  (9)
    "Data Steward",          // K  (10)
    "Organisational Unit",   // L  (11)
    "CBA Flag",              // M  (12)
    "CBA Rationale",         // N  (13)
    "External Reference ID", // O  (14)
];

/// Instructions for each column (field, description, mandatory, max_length, notes).
const INSTRUCTIONS: &[(&str, &str, &str, &str, &str)] = &[
    (
        "Application Name",
        "The official name of the business application",
        "Yes",
        "256",
        "Must be unique",
    ),
    (
        "Description",
        "Clear description of what the application does",
        "Yes",
        "4000",
        "Plain text only",
    ),
    (
        "Classification",
        "Application classification category",
        "Yes",
        "",
        "Select from dropdown",
    ),
    ("Vendor", "Name of the software vendor", "Yes", "256", ""),
    (
        "Vendor Product Name",
        "Commercial product name from the vendor",
        "Yes",
        "256",
        "",
    ),
    (
        "Deployment Type",
        "How the application is deployed",
        "Yes",
        "",
        "ON_PREMISE, CLOUD, HYBRID, or SAAS",
    ),
    (
        "Lifecycle Stage",
        "Current stage of the application lifecycle",
        "Yes",
        "",
        "Select from dropdown",
    ),
    (
        "License Type",
        "Type of software license",
        "Yes",
        "256",
        "e.g. Perpetual, Subscription, Open Source",
    ),
    (
        "Business Owner",
        "Email address of the business owner",
        "Yes",
        "",
        "Must exist in the system",
    ),
    (
        "Technical Owner",
        "Email address of the technical owner",
        "Yes",
        "",
        "Must exist in the system",
    ),
    (
        "Data Steward",
        "Email address of the data steward",
        "Yes",
        "",
        "Must exist in the system",
    ),
    (
        "Organisational Unit",
        "Responsible organisational unit",
        "Yes",
        "",
        "Select from dropdown",
    ),
    (
        "CBA Flag",
        "Whether this is a Critical Business Application",
        "No",
        "",
        "TRUE or FALSE",
    ),
    (
        "CBA Rationale",
        "Justification for CBA designation",
        "Conditional",
        "4000",
        "Required if CBA Flag = TRUE",
    ),
    (
        "External Reference ID",
        "External system reference identifier",
        "Yes",
        "256",
        "e.g. CMDB ID, ServiceNow CI",
    ),
];

// ---------------------------------------------------------------------------
// Template download
// ---------------------------------------------------------------------------

/// Download an Excel template for bulk-uploading business applications.
///
/// Returns a `.xlsx` file with three sheets: Applications (data entry with dropdowns),
/// Valid Values (lookup lists from the database), and Instructions (field documentation).
/// Dropdown validations reference the Valid Values sheet, ensuring data integrity.
#[utoipa::path(
    get,
    path = "/api/v1/applications/bulk-upload/template",
    responses(
        (status = 200, description = "Excel template file", content_type = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
    ),
    security(("bearer_auth" = [])),
    tag = "applications"
)]
pub async fn download_app_template(State(state): State<AppState>) -> AppResult<Response> {
    let bytes = generate_template(&state.pool).await?;

    Response::builder()
        .status(StatusCode::OK)
        .header(
            header::CONTENT_TYPE,
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        )
        .header(
            header::CONTENT_DISPOSITION,
            "attachment; filename=\"application_bulk_upload_template.xlsx\"",
        )
        .body(Body::from(bytes))
        .map_err(|e| AppError::Internal(anyhow::anyhow!("failed to build response: {e}")))
}

/// Fetch all lookup values from DB and build the Excel template in memory.
async fn generate_template(pool: &PgPool) -> AppResult<Vec<u8>> {
    // Fetch all lookup lists in parallel
    let (classifications, lifecycle_stages, org_units, users_list) = tokio::try_join!(
        fetch_names(
            pool,
            "SELECT classification_name FROM application_classifications ORDER BY display_order"
        ),
        fetch_names(
            pool,
            "SELECT stage_name FROM application_lifecycle_stages ORDER BY display_order"
        ),
        fetch_names(
            pool,
            "SELECT unit_name FROM organisational_units ORDER BY display_order"
        ),
        fetch_names(
            pool,
            "SELECT email FROM users WHERE is_active = TRUE ORDER BY display_name"
        ),
    )?;

    let mut workbook = Workbook::new();

    // --- Formats ---
    let header_format = Format::new()
        .set_bold()
        .set_background_color(rust_xlsxwriter::Color::RGB(0x4472C4))
        .set_font_color(rust_xlsxwriter::Color::White)
        .set_align(FormatAlign::Center)
        .set_border(FormatBorder::Thin);

    let mandatory_header_format = Format::new()
        .set_bold()
        .set_background_color(rust_xlsxwriter::Color::RGB(0xFFC000))
        .set_font_color(rust_xlsxwriter::Color::Black)
        .set_align(FormatAlign::Center)
        .set_border(FormatBorder::Thin);

    let instruction_header_format = Format::new()
        .set_bold()
        .set_background_color(rust_xlsxwriter::Color::RGB(0x305496))
        .set_font_color(rust_xlsxwriter::Color::White)
        .set_border(FormatBorder::Thin);

    let list_header_format = Format::new()
        .set_bold()
        .set_background_color(rust_xlsxwriter::Color::RGB(0x305496))
        .set_font_color(rust_xlsxwriter::Color::White)
        .set_border(FormatBorder::Thin);

    // Mandatory column indices: A(0) through M(12) and P(15). N(13) and O(14) are optional/conditional.
    let mandatory_cols: &[u16] = &[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15];

    // Each lookup list with its name
    let lookup_lists: Vec<(&str, &[String])> = vec![
        ("Classifications", &classifications),  // 0
        ("LifecycleStages", &lifecycle_stages), // 1
        ("OrganisationalUnits", &org_units),    // 2
        ("Users", &users_list),                 // 3
    ];

    // Dropdown column mappings: (Applications column index, lookup list index)
    let dropdown_mappings: &[(u16, usize)] = &[
        (2, 0),  // Classification     -> Classifications
        (6, 1),  // Lifecycle Stage     -> LifecycleStages
        (8, 3),  // Business Owner      -> Users
        (9, 3),  // Technical Owner     -> Users
        (10, 3), // Data Steward        -> Users
        (11, 2), // Organisational Unit -> OrganisationalUnits
    ];

    // Pre-build the data validations (no borrow on workbook needed yet)
    let mut validations: Vec<(u16, DataValidation)> = Vec::new();
    for &(app_col, lookup_idx) in dropdown_mappings {
        let (_name, values) = &lookup_lists[lookup_idx];
        if !values.is_empty() {
            let last_row = values.len() as u32;
            let col_letter = col_to_letter(lookup_idx as u16);
            let formula_str = format!(
                "='Valid Values'!${col_letter}$2:${col_letter}${}",
                last_row + 1
            );
            let validation = DataValidation::new()
                .allow_list_formula(Formula::new(formula_str))
                .set_error_title("Invalid value")
                .map_err(xlsx_err)?
                .set_error_message("Please select a value from the dropdown list.")
                .map_err(xlsx_err)?;
            validations.push((app_col, validation));
        }
    }

    // Deployment type dropdown (static list)
    let deployment_validation = DataValidation::new()
        .allow_list_strings(&["ON_PREMISE", "CLOUD", "HYBRID", "SAAS"])
        .map_err(xlsx_err)?
        .set_error_title("Invalid value")
        .map_err(xlsx_err)?
        .set_error_message("Please enter ON_PREMISE, CLOUD, HYBRID, or SAAS.")
        .map_err(xlsx_err)?;

    // CBA Flag dropdown (static list)
    let cba_validation = DataValidation::new()
        .allow_list_strings(&["TRUE", "FALSE"])
        .map_err(xlsx_err)?
        .set_error_title("Invalid value")
        .map_err(xlsx_err)?
        .set_error_message("Please enter TRUE or FALSE.")
        .map_err(xlsx_err)?;

    // ===== Sheet 1: Applications =====
    {
        let app_sheet = workbook.add_worksheet();
        app_sheet.set_name("Applications").map_err(xlsx_err)?;

        // Write headers
        for (col, &hdr) in TEMPLATE_HEADERS.iter().enumerate() {
            let col = col as u16;
            let fmt = if mandatory_cols.contains(&col) {
                &mandatory_header_format
            } else {
                &header_format
            };
            app_sheet
                .write_string_with_format(0, col, hdr, fmt)
                .map_err(xlsx_err)?;
            app_sheet.set_column_width(col, 22).map_err(xlsx_err)?;
        }
        app_sheet.set_column_width(0, 30).map_err(xlsx_err)?; // Application Name
        app_sheet.set_column_width(1, 50).map_err(xlsx_err)?; // Description
        app_sheet.set_column_width(14, 40).map_err(xlsx_err)?; // CBA Rationale

        // Apply data validations from lookup lists
        for (app_col, validation) in &validations {
            app_sheet
                .add_data_validation(1, *app_col, MAX_ROWS as u32, *app_col, validation)
                .map_err(xlsx_err)?;
        }

        // Deployment Type validation (col F = 5)
        app_sheet
            .add_data_validation(1, 5, MAX_ROWS as u32, 5, &deployment_validation)
            .map_err(xlsx_err)?;

        // CBA Flag validation (col N = 13)
        app_sheet
            .add_data_validation(1, 13, MAX_ROWS as u32, 13, &cba_validation)
            .map_err(xlsx_err)?;
    }

    // ===== Sheet 2: Valid Values =====
    {
        let valid_sheet = workbook.add_worksheet();
        valid_sheet.set_name("Valid Values").map_err(xlsx_err)?;

        for (col_idx, (name, values)) in lookup_lists.iter().enumerate() {
            let col = col_idx as u16;
            valid_sheet
                .write_string_with_format(0, col, *name, &list_header_format)
                .map_err(xlsx_err)?;
            valid_sheet.set_column_width(col, 30).map_err(xlsx_err)?;
            for (row_idx, val) in values.iter().enumerate() {
                valid_sheet
                    .write_string((row_idx + 1) as u32, col, val)
                    .map_err(xlsx_err)?;
            }
        }
    }

    // ===== Sheet 3: Instructions =====
    {
        let instr_sheet = workbook.add_worksheet();
        instr_sheet.set_name("Instructions").map_err(xlsx_err)?;

        let instr_headers = [
            "Field Name",
            "Description",
            "Mandatory",
            "Max Length",
            "Notes",
        ];
        for (col, &hdr) in instr_headers.iter().enumerate() {
            instr_sheet
                .write_string_with_format(0, col as u16, hdr, &instruction_header_format)
                .map_err(xlsx_err)?;
        }
        instr_sheet.set_column_width(0, 25).map_err(xlsx_err)?;
        instr_sheet.set_column_width(1, 55).map_err(xlsx_err)?;
        instr_sheet.set_column_width(2, 12).map_err(xlsx_err)?;
        instr_sheet.set_column_width(3, 12).map_err(xlsx_err)?;
        instr_sheet.set_column_width(4, 40).map_err(xlsx_err)?;

        for (row_idx, &(field, desc, mandatory, max_len, notes)) in INSTRUCTIONS.iter().enumerate()
        {
            let row = (row_idx + 1) as u32;
            instr_sheet.write_string(row, 0, field).map_err(xlsx_err)?;
            instr_sheet.write_string(row, 1, desc).map_err(xlsx_err)?;
            instr_sheet
                .write_string(row, 2, mandatory)
                .map_err(xlsx_err)?;
            instr_sheet
                .write_string(row, 3, max_len)
                .map_err(xlsx_err)?;
            instr_sheet.write_string(row, 4, notes).map_err(xlsx_err)?;
        }
    }

    // Save to buffer
    let buf = workbook.save_to_buffer().map_err(xlsx_err)?;
    Ok(buf)
}

/// Fetch a single-column list of names from the database.
async fn fetch_names(pool: &PgPool, query: &str) -> AppResult<Vec<String>> {
    let rows = sqlx::query_scalar::<_, String>(query)
        .fetch_all(pool)
        .await?;
    Ok(rows)
}

/// Convert 0-based column index to Excel column letter(s).
fn col_to_letter(col: u16) -> String {
    let mut result = String::new();
    let mut n = col as u32;
    loop {
        result.insert(0, (b'A' + (n % 26) as u8) as char);
        if n < 26 {
            break;
        }
        n = n / 26 - 1;
    }
    result
}

/// Convert `rust_xlsxwriter` errors to `AppError`.
fn xlsx_err(e: rust_xlsxwriter::XlsxError) -> AppError {
    AppError::Internal(anyhow::anyhow!("excel generation error: {e}"))
}

// ---------------------------------------------------------------------------
// Bulk upload
// ---------------------------------------------------------------------------

/// Bulk-upload business applications from a filled-in Excel template.
///
/// Accepts a multipart file upload (max 10 MB, up to 1000 rows). Each row is
/// processed independently — partial success is supported. Created applications
/// enter the DRAFT workflow state. No AI enrichment is triggered. Each successful
/// insert is recorded in the `audit_log` table.
#[utoipa::path(
    post,
    path = "/api/v1/applications/bulk-upload",
    request_body(content_type = "multipart/form-data", content = String, description = "Excel file upload"),
    responses(
        (status = 200, description = "Upload results", body = BulkUploadResult),
        (status = 413, description = "File too large"),
        (status = 422, description = "Invalid file format")
    ),
    security(("bearer_auth" = [])),
    tag = "applications"
)]
pub async fn bulk_upload_apps(
    State(state): State<AppState>,
    Extension(claims): Extension<Claims>,
    mut multipart: Multipart,
) -> AppResult<axum::Json<BulkUploadResult>> {
    // Extract the file from multipart
    let mut file_bytes: Option<Vec<u8>> = None;
    let mut file_name: Option<String> = None;
    let mut content_type: Option<String> = None;

    while let Some(field) = multipart
        .next_field()
        .await
        .map_err(|e| AppError::BadRequest(format!("multipart error: {e}")))?
    {
        let name = field.name().unwrap_or("").to_string();
        if name == "file" {
            file_name = field.file_name().map(|s| s.to_string());
            content_type = field.content_type().map(|s| s.to_string());
            let data = field
                .bytes()
                .await
                .map_err(|e| AppError::BadRequest(format!("failed to read file: {e}")))?;
            file_bytes = Some(data.to_vec());
            break;
        }
    }

    let file_bytes = file_bytes
        .ok_or_else(|| AppError::BadRequest("no file field found in multipart upload".into()))?;

    // SEC-024: Validate content type and file extension before processing
    let valid_content_types = [
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "application/vnd.ms-excel",
        "application/octet-stream", // browsers sometimes send this for xlsx
    ];
    let has_valid_content_type = content_type
        .as_deref()
        .map(|ct| valid_content_types.iter().any(|v| ct.starts_with(v)))
        .unwrap_or(true); // if no content type, fall through to format check below
    let has_valid_extension = file_name
        .as_deref()
        .map(|name| name.to_lowercase().ends_with(".xlsx") || name.to_lowercase().ends_with(".xls"))
        .unwrap_or(true); // if no filename, fall through to format check below

    if !has_valid_content_type && !has_valid_extension {
        return Err(AppError::Validation(
            "invalid file type — only .xlsx (Excel) files are accepted".into(),
        ));
    }

    // Check file size
    if file_bytes.len() > MAX_FILE_SIZE {
        return Err(AppError::Validation(format!(
            "file exceeds maximum size of {} MB",
            MAX_FILE_SIZE / (1024 * 1024)
        )));
    }

    // Parse the Excel file
    let cursor = Cursor::new(&file_bytes);
    let mut workbook: Xlsx<_> = open_workbook_from_rs(cursor)
        .map_err(|e| AppError::Validation(format!("invalid Excel file: {e}")))?;

    // Read the "Applications" sheet
    let range = workbook
        .worksheet_range("Applications")
        .map_err(|e| AppError::Validation(format!("cannot read 'Applications' sheet: {e}")))?;

    let rows: Vec<Vec<Data>> = range.rows().map(|r| r.to_vec()).collect();

    if rows.is_empty() {
        return Err(AppError::Validation("applications sheet is empty".into()));
    }

    // Validate header row
    let header_row = &rows[0];
    for (i, &expected) in TEMPLATE_HEADERS.iter().enumerate() {
        let actual = cell_as_string(header_row.get(i));
        if actual.trim().to_lowercase() != expected.to_lowercase() {
            return Err(AppError::Validation(format!(
                "column {} header mismatch: expected '{}', found '{}'",
                col_to_letter(i as u16),
                expected,
                actual
            )));
        }
    }

    // Collect data rows (skip header, stop at first completely empty row)
    let mut data_rows: Vec<(usize, Vec<String>)> = Vec::new();
    for (idx, row) in rows.iter().enumerate().skip(1) {
        if idx > MAX_ROWS {
            break;
        }
        // Check if row is completely empty
        let all_empty = row.iter().all(|cell| {
            matches!(cell, Data::Empty) || cell_as_string(Some(cell)).trim().is_empty()
        });
        if all_empty {
            break;
        }
        let string_row: Vec<String> = (0..TEMPLATE_HEADERS.len())
            .map(|col| cell_as_string(row.get(col)))
            .collect();
        data_rows.push((idx + 1, string_row)); // 1-based row number (header = row 1)
    }

    if data_rows.is_empty() {
        return Ok(axum::Json(BulkUploadResult {
            total_rows: 0,
            successful: 0,
            failed: 0,
            errors: vec![],
            created_term_ids: vec![],
        }));
    }

    // Fetch DRAFT status_id
    let draft_status_id = sqlx::query_scalar::<_, Uuid>(
        "SELECT status_id FROM entity_statuses WHERE status_code = 'DRAFT'",
    )
    .fetch_one(&state.pool)
    .await?;

    let ctx = AppBulkUploadContext {
        pool: &state.pool,
        user_id: claims.sub,
        draft_status_id,
    };

    let total_rows = data_rows.len();
    let mut successful = 0usize;
    let mut errors: Vec<BulkUploadError> = Vec::new();
    let mut created_app_ids: Vec<Uuid> = Vec::new();

    // Process each row independently
    for (row_num, cols) in &data_rows {
        let row_result = process_app_row(&ctx, *row_num, cols, &mut created_app_ids).await;

        match row_result {
            Ok(()) => {
                successful += 1;
            }
            Err(mut errs) => {
                errors.append(&mut errs);
            }
        }
    }

    Ok(axum::Json(BulkUploadResult {
        total_rows,
        successful,
        failed: total_rows - successful,
        errors,
        created_term_ids: created_app_ids,
    }))
}

/// Context passed to each row during bulk upload processing.
struct AppBulkUploadContext<'a> {
    pool: &'a PgPool,
    user_id: Uuid,
    draft_status_id: Uuid,
}

/// Process a single row from the upload. Returns Ok(()) on success,
/// or Err(Vec<BulkUploadError>) with all validation errors for this row.
async fn process_app_row(
    ctx: &AppBulkUploadContext<'_>,
    row_num: usize,
    cols: &[String],
    created_ids: &mut Vec<Uuid>,
) -> Result<(), Vec<BulkUploadError>> {
    let mut row_errors: Vec<BulkUploadError> = Vec::new();

    // --- Extract and trim values ---
    let application_name = cols[0].trim().to_string();
    let description = cols[1].trim().to_string();
    let classification_val = cols[2].trim().to_string();
    let vendor = cols[3].trim().to_string();
    let vendor_product_name = cols[4].trim().to_string();
    let deployment_type = cols[5].trim().to_string();
    let lifecycle_stage_val = cols[6].trim().to_string();
    let license_type = cols[7].trim().to_string();
    let business_owner_email = cols[8].trim().to_string();
    let technical_owner_email = cols[9].trim().to_string();
    let steward_email = cols[10].trim().to_string();
    let org_unit_val = cols[11].trim().to_string();
    let cba_flag_str = non_empty(&cols[12]);
    let cba_rationale = non_empty(&cols[13]);
    let external_reference_id = cols[14].trim().to_string();

    // --- Mandatory field validation ---
    if application_name.is_empty() {
        row_errors.push(BulkUploadError {
            row: row_num,
            field: Some("Application Name".into()),
            message: "Application Name is required".into(),
        });
    }
    if description.is_empty() {
        row_errors.push(BulkUploadError {
            row: row_num,
            field: Some("Description".into()),
            message: "Description is required".into(),
        });
    }
    if classification_val.is_empty() {
        row_errors.push(BulkUploadError {
            row: row_num,
            field: Some("Classification".into()),
            message: "Classification is required".into(),
        });
    }
    if vendor.is_empty() {
        row_errors.push(BulkUploadError {
            row: row_num,
            field: Some("Vendor".into()),
            message: "Vendor is required".into(),
        });
    }
    if vendor_product_name.is_empty() {
        row_errors.push(BulkUploadError {
            row: row_num,
            field: Some("Vendor Product Name".into()),
            message: "Vendor Product Name is required".into(),
        });
    }
    if deployment_type.is_empty() {
        row_errors.push(BulkUploadError {
            row: row_num,
            field: Some("Deployment Type".into()),
            message: "Deployment Type is required".into(),
        });
    }
    if lifecycle_stage_val.is_empty() {
        row_errors.push(BulkUploadError {
            row: row_num,
            field: Some("Lifecycle Stage".into()),
            message: "Lifecycle Stage is required".into(),
        });
    }
    if license_type.is_empty() {
        row_errors.push(BulkUploadError {
            row: row_num,
            field: Some("License Type".into()),
            message: "License Type is required".into(),
        });
    }
    if business_owner_email.is_empty() {
        row_errors.push(BulkUploadError {
            row: row_num,
            field: Some("Business Owner".into()),
            message: "Business Owner email is required".into(),
        });
    }
    if technical_owner_email.is_empty() {
        row_errors.push(BulkUploadError {
            row: row_num,
            field: Some("Technical Owner".into()),
            message: "Technical Owner email is required".into(),
        });
    }
    if steward_email.is_empty() {
        row_errors.push(BulkUploadError {
            row: row_num,
            field: Some("Data Steward".into()),
            message: "Data Steward email is required".into(),
        });
    }
    if org_unit_val.is_empty() {
        row_errors.push(BulkUploadError {
            row: row_num,
            field: Some("Organisational Unit".into()),
            message: "Organisational Unit is required".into(),
        });
    }
    if external_reference_id.is_empty() {
        row_errors.push(BulkUploadError {
            row: row_num,
            field: Some("External Reference ID".into()),
            message: "External Reference ID is required".into(),
        });
    }

    // --- Length validations ---
    if application_name.len() > 256 {
        row_errors.push(BulkUploadError {
            row: row_num,
            field: Some("Application Name".into()),
            message: "Application Name exceeds 256 characters".into(),
        });
    }
    if description.len() > 4000 {
        row_errors.push(BulkUploadError {
            row: row_num,
            field: Some("Description".into()),
            message: "Description exceeds 4000 characters".into(),
        });
    }
    if vendor.len() > 256 {
        row_errors.push(BulkUploadError {
            row: row_num,
            field: Some("Vendor".into()),
            message: "Vendor exceeds 256 characters".into(),
        });
    }
    if vendor_product_name.len() > 256 {
        row_errors.push(BulkUploadError {
            row: row_num,
            field: Some("Vendor Product Name".into()),
            message: "Vendor Product Name exceeds 256 characters".into(),
        });
    }
    if license_type.len() > 256 {
        row_errors.push(BulkUploadError {
            row: row_num,
            field: Some("License Type".into()),
            message: "License Type exceeds 256 characters".into(),
        });
    }
    if external_reference_id.len() > 256 {
        row_errors.push(BulkUploadError {
            row: row_num,
            field: Some("External Reference ID".into()),
            message: "External Reference ID exceeds 256 characters".into(),
        });
    }

    // --- Validate deployment type enum ---
    if !deployment_type.is_empty()
        && !["ON_PREMISE", "CLOUD", "HYBRID", "SAAS"].contains(&deployment_type.as_str())
    {
        row_errors.push(BulkUploadError {
            row: row_num,
            field: Some("Deployment Type".into()),
            message: format!(
                "'{}' is not a valid Deployment Type — must be ON_PREMISE, CLOUD, HYBRID, or SAAS",
                deployment_type
            ),
        });
    }

    // --- Validate CBA rationale is present when CBA flag is TRUE ---
    let is_cba = cba_flag_str
        .as_deref()
        .map(|s| s.eq_ignore_ascii_case("true"))
        .unwrap_or(false);

    if is_cba && cba_rationale.is_none() {
        row_errors.push(BulkUploadError {
            row: row_num,
            field: Some("CBA Rationale".into()),
            message: "CBA Rationale is required when CBA Flag is TRUE".into(),
        });
    }
    if cba_rationale.as_ref().is_some_and(|v| v.len() > 4000) {
        row_errors.push(BulkUploadError {
            row: row_num,
            field: Some("CBA Rationale".into()),
            message: "CBA Rationale exceeds 4000 characters".into(),
        });
    }

    // --- Resolve lookups ---
    let classification_opt = non_empty(&classification_val);
    let classification_id = resolve_optional_lookup(
        ctx.pool, row_num, "Classification", &classification_opt,
        "SELECT classification_id FROM application_classifications WHERE classification_name ILIKE $1",
        &mut row_errors,
    ).await;

    let lifecycle_opt = non_empty(&lifecycle_stage_val);
    let lifecycle_stage_id = resolve_optional_lookup(
        ctx.pool,
        row_num,
        "Lifecycle Stage",
        &lifecycle_opt,
        "SELECT stage_id FROM application_lifecycle_stages WHERE stage_name ILIKE $1",
        &mut row_errors,
    )
    .await;

    // Resolve organisational unit — validate it exists in lookup table
    if !org_unit_val.is_empty() {
        let ou_exists = sqlx::query_scalar::<_, bool>(
            "SELECT EXISTS(SELECT 1 FROM organisational_units WHERE unit_name ILIKE $1)",
        )
        .bind(&org_unit_val)
        .fetch_one(ctx.pool)
        .await
        .unwrap_or(false);

        if !ou_exists {
            row_errors.push(BulkUploadError {
                row: row_num,
                field: Some("Organisational Unit".into()),
                message: format!("'{}' is not a valid Organisational Unit", org_unit_val),
            });
        }
    }

    // Resolve users by email
    let business_owner_id = resolve_user_by_email(
        ctx.pool,
        row_num,
        "Business Owner",
        &business_owner_email,
        &mut row_errors,
    )
    .await;
    let technical_owner_id = resolve_user_by_email(
        ctx.pool,
        row_num,
        "Technical Owner",
        &technical_owner_email,
        &mut row_errors,
    )
    .await;
    let steward_user_id = resolve_user_by_email(
        ctx.pool,
        row_num,
        "Data Steward",
        &steward_email,
        &mut row_errors,
    )
    .await;
    // If there are validation errors, return them all
    if !row_errors.is_empty() {
        return Err(row_errors);
    }

    // --- Insert the application ---
    // application_code is NULL → DB trigger auto-generates it
    let app_id = sqlx::query_scalar::<_, Uuid>(
        r#"
        INSERT INTO applications (
            application_name, description,
            classification_id, vendor, vendor_product_name,
            deployment_type, lifecycle_stage_id, license_type,
            business_owner_id, technical_owner_id,
            steward_user_id,
            organisational_unit,
            is_cba, cba_rationale,
            external_reference_id,
            status_id, created_by
        )
        VALUES (
            $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
            $11, $12, $13, $14, $15, $16, $17
        )
        RETURNING application_id
        "#,
    )
    .bind(&application_name)          // $1
    .bind(&description)               // $2
    .bind(classification_id)          // $3
    .bind(&vendor)                    // $4
    .bind(&vendor_product_name)       // $5
    .bind(&deployment_type)           // $6
    .bind(lifecycle_stage_id)         // $7
    .bind(&license_type)             // $8
    .bind(business_owner_id)          // $9
    .bind(technical_owner_id)         // $10
    .bind(steward_user_id)            // $11
    .bind(&org_unit_val)              // $12
    .bind(is_cba)                     // $13
    .bind(cba_rationale.as_deref())   // $14
    .bind(&external_reference_id)     // $15
    .bind(ctx.draft_status_id)        // $16
    .bind(ctx.user_id)                // $17
    .fetch_one(ctx.pool)
    .await
    .map_err(|e| {
        vec![BulkUploadError {
            row: row_num,
            field: None,
            message: format!("database insert failed: {e}"),
        }]
    })?;

    // Initiate workflow
    if let Err(e) = workflow::service::initiate_workflow(
        ctx.pool,
        workflow::ENTITY_APPLICATION,
        app_id,
        ctx.user_id,
    )
    .await
    {
        tracing::warn!(app_id = %app_id, error = %e, "failed to initiate workflow for bulk-uploaded application");
    }

    // CS-003: Audit log entry for bulk-uploaded application
    sqlx::query(
        "INSERT INTO audit_log (table_name, record_id, action, new_values, changed_by) \
         VALUES ('applications', $1, 'INSERT', $2, $3)",
    )
    .bind(app_id)
    .bind(serde_json::json!({"source": "bulk_upload", "row": row_num}))
    .bind(ctx.user_id)
    .execute(ctx.pool)
    .await
    .ok(); // Don't fail the upload if audit logging fails

    created_ids.push(app_id);
    Ok(())
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Extract a trimmed string from a calamine `Data` cell value.
fn cell_as_string(cell: Option<&Data>) -> String {
    match cell {
        Some(Data::String(s)) => s.trim().to_string(),
        Some(Data::Float(f)) => {
            // Excel sometimes stores integers as floats
            if (*f - f.round()).abs() < f64::EPSILON {
                format!("{}", *f as i64)
            } else {
                format!("{f}")
            }
        }
        Some(Data::Int(i)) => format!("{i}"),
        Some(Data::Bool(b)) => {
            if *b {
                "TRUE".into()
            } else {
                "FALSE".into()
            }
        }
        Some(Data::DateTime(f)) => format!("{f}"),
        Some(Data::DateTimeIso(s)) => s.clone(),
        Some(Data::DurationIso(s)) => s.clone(),
        Some(Data::Error(e)) => format!("{e:?}"),
        Some(Data::Empty) | None => String::new(),
    }
}

/// Return Some(trimmed) if the string is non-empty, None otherwise.
fn non_empty(s: &str) -> Option<String> {
    let trimmed = s.trim();
    if trimmed.is_empty() {
        None
    } else {
        Some(trimmed.to_string())
    }
}

/// Resolve an optional lookup value (display name -> UUID).
/// If the value is provided but not found, pushes an error.
async fn resolve_optional_lookup(
    pool: &PgPool,
    row_num: usize,
    field_name: &str,
    value: &Option<String>,
    query: &str,
    errors: &mut Vec<BulkUploadError>,
) -> Option<Uuid> {
    let val = match value {
        Some(v) if !v.is_empty() => v,
        _ => return None,
    };

    // Try UUID parse first (in case someone pastes a UUID)
    if let Ok(id) = Uuid::parse_str(val) {
        return Some(id);
    }

    let result = sqlx::query_scalar::<_, Uuid>(query)
        .bind(val)
        .fetch_optional(pool)
        .await;

    match result {
        Ok(Some(id)) => Some(id),
        Ok(None) => {
            errors.push(BulkUploadError {
                row: row_num,
                field: Some(field_name.into()),
                message: format!("'{}' is not a valid {}", val, field_name),
            });
            None
        }
        Err(e) => {
            errors.push(BulkUploadError {
                row: row_num,
                field: Some(field_name.into()),
                message: format!("Failed to resolve {}: {}", field_name, e),
            });
            None
        }
    }
}

/// Resolve a user by email address.
async fn resolve_user_by_email(
    pool: &PgPool,
    row_num: usize,
    field_name: &str,
    email: &str,
    errors: &mut Vec<BulkUploadError>,
) -> Option<Uuid> {
    if email.is_empty() {
        return None; // mandatory check is done separately
    }

    let result = sqlx::query_scalar::<_, Uuid>(
        "SELECT user_id FROM users WHERE email ILIKE $1 AND is_active = TRUE",
    )
    .bind(email)
    .fetch_optional(pool)
    .await;

    match result {
        Ok(Some(id)) => Some(id),
        Ok(None) => {
            errors.push(BulkUploadError {
                row: row_num,
                field: Some(field_name.into()),
                message: format!("User with email '{}' not found", email),
            });
            None
        }
        Err(e) => {
            errors.push(BulkUploadError {
                row: row_num,
                field: Some(field_name.into()),
                message: format!("Failed to resolve user: {}", e),
            });
            None
        }
    }
}
